require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'


pod 'GoogleSignIn', '~> 5.0.2'
# Override Firebase SDK Version
$FirebaseSDKVersion = '8.9.1'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
# $RNFirebaseAnalyticsWithoutAdIdSupport=true

target 'happify' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
     end
    end
   end

  target 'happifyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.75.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  #   react_native_post_install(installer)
  # end
end
